# Generated by Django 5.1.15 on 2026-04-30 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_rename_services_re_service_created_idx_services_re_service_0e1fa6_idx_and_more'),
        ('users', '0003_rename_users_provi_is_veri_rating_idx_users_provi_is_veri_d41171_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(db_index=True, verbose_name='scheduled date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12, verbose_name='status')),
                ('total_price', models.DecimalField(decimal_places=2, help_text="Frozen at booking time so subsequent service-price changes don't retroactively alter outstanding bookings.", max_digits=10, verbose_name='total price')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('customer', models.ForeignKey(help_text='The User (role=customer) who placed the booking.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('provider', models.ForeignKey(help_text='Denormalised from ``service.provider`` so booking lists can be filtered by provider without joining through Service.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='users.providerprofile', verbose_name='provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ('-scheduled_date', '-start_time'),
                'abstract': False,
                'indexes': [models.Index(fields=['provider', 'scheduled_date'], name='bookings_bo_provide_0c6fc2_idx'), models.Index(fields=['customer', '-scheduled_date'], name='bookings_bo_custome_11543e_idx'), models.Index(fields=['status', '-scheduled_date'], name='bookings_bo_status_a44f04_idx')],
            },
        ),
    ]
