# Generated by Django 5.1.15 on 2026-04-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='service',
            new_name='services_se_is_acti_b3b6ee_idx',
            old_name='services_se_is_acti_a3d2c4_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='services_se_is_acti_2d83d4_idx',
            old_name='services_se_is_acti_b41f57_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecategory',
            new_name='services_se_is_acti_79641e_idx',
            old_name='services_se_is_acti_70ed16_idx',
        ),
    ]
