# Generated by Django 5.1.15 on 2026-04-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_marketplace_fields_and_review'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='services_re_service_0e1fa6_idx',
            old_name='services_re_service_created_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='services_re_is_publ_fb2aa5_idx',
            old_name='services_re_pub_created_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='services_se_is_acti_bfbbaa_idx',
            old_name='services_se_is_acti_feat_idx',
        ),
    ]
