# Generated by Django 5.1.15 on 2026-05-07

import decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_rename_services_re_service_created_idx_services_re_service_0e1fa6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_location_name",
            field=models.CharField(
                blank=True,
                help_text="Optional display name for the service location.",
                max_length=180,
                verbose_name="service location name",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_address",
            field=models.CharField(
                blank=True,
                help_text="Street address used for map display and geocoding.",
                max_length=255,
                verbose_name="service address",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_city",
            field=models.CharField(
                blank=True,
                max_length=120,
                verbose_name="service city",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_country",
            field=models.CharField(
                blank=True,
                max_length=120,
                verbose_name="service country",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude coordinate for map display.",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(decimal.Decimal("-90.000000")),
                    django.core.validators.MaxValueValidator(decimal.Decimal("90.000000")),
                ],
                verbose_name="latitude",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude coordinate for map display.",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(decimal.Decimal("-180.000000")),
                    django.core.validators.MaxValueValidator(decimal.Decimal("180.000000")),
                ],
                verbose_name="longitude",
            ),
        ),
    ]
