# Generated by Django 5.1.15 on 2026-04-22 15:25

import apps.users.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider'), ('admin', 'Admin')], db_index=True, default='customer', max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255, verbose_name='business name')),
                ('business_type', models.CharField(choices=[('individual', 'Individual / Sole Trader'), ('llc', 'LLC'), ('corporation', 'Corporation'), ('partnership', 'Partnership'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], default='individual', max_length=32, verbose_name='business type')),
                ('tax_id', models.CharField(blank=True, help_text='EIN, VAT, company registration number, etc.', max_length=64, verbose_name='tax / registration ID')),
                ('phone_number', models.CharField(max_length=32, verbose_name='phone number')),
                ('service_category', models.CharField(max_length=128, verbose_name='primary service category')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0, verbose_name='years of experience')),
                ('service_area', models.CharField(help_text='City, region, or radius the provider operates in.', max_length=255, verbose_name='service area')),
                ('short_bio', models.TextField(blank=True, verbose_name='short bio')),
                ('license_or_certification_number', models.CharField(blank=True, max_length=128, verbose_name='license or certification number')),
                ('insurance_provider', models.CharField(blank=True, max_length=128, verbose_name='insurance provider')),
                ('is_verified', models.BooleanField(default=False, help_text='Set by admins once KYC / onboarding documentation is reviewed.', verbose_name='verified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'provider profile',
                'verbose_name_plural': 'provider profiles',
                'ordering': ('-created_at',),
            },
        ),
    ]
