# Generated by Django 5.1.15 on 2026-04-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_marketplace_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='providerprofile',
            new_name='users_provi_is_veri_d41171_idx',
            old_name='users_provi_is_veri_rating_idx',
        ),
    ]
