# Generated by Django 5.1.15 on 2026-04-30 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_rename_users_provi_is_veri_rating_idx_users_provi_is_veri_d41171_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('is_available', models.BooleanField(default=False, help_text='True extends the recurring schedule with an ad-hoc slot; False blocks a window that the recurring schedule would otherwise expose (vacation, sick day, fully-booked).', verbose_name='is available')),
                ('reason', models.CharField(blank=True, max_length=160, verbose_name='reason')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='users.providerprofile', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'availability exception',
                'verbose_name_plural': 'availability exceptions',
                'ordering': ('date', 'start_time'),
                'abstract': False,
                'indexes': [models.Index(fields=['provider', 'date'], name='scheduling__provide_6ee04d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='scheduling_exception_start_before_end')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True, verbose_name='weekday')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='users.providerprofile', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'weekly availability',
                'verbose_name_plural': 'weekly availability',
                'ordering': ('weekday', 'start_time'),
                'abstract': False,
                'indexes': [models.Index(fields=['provider', 'weekday'], name='scheduling__provide_1a058c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='scheduling_weekly_start_before_end'), models.UniqueConstraint(fields=('provider', 'weekday', 'start_time', 'end_time'), name='scheduling_weekly_unique_slot')],
            },
        ),
    ]
